config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/about'=> 'home#about'
  get '/help' => 'home#help'
  get '/login' => 'home#login'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :seller
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  #metoda koja prosljedjuje simbole
  has_one :profile, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  #  @developers=[
      #'Neldin',
      #'Tarik',
      #'Aida',
      #'Selma'
    #]
    #izvuci sve proizvode i ispisati ih na view
    #@products=Product.all
    developers = [
      Developer.new('Ivan','Kovac',['ruby','php']),
      Developer.new('Ivan2','Kovac2',['rails','php']),
      Developer.new('Ivan3','Kovac3',['ruby','php'])
    ]

    @devs=  []
    #ispitivanje da li taj param postoji blank ispituje da li je nil, false, prazni navodnici
    if params[:filter].present?
     developers.map do |dev|
       @devs << dev if dev.has_skill?(params[:filter])
     end
    else
     @devs=developers
    end
  end


  def login
    puts params.inspect


    if params[:username] == 'ivan' && params[:password] == '1234'
      redirect_to root_path
    else
      redirect_to help_path
    end
  end

  def about
    developers = [
      Developer.new('Ivan','Kovac',['ruby','php']),
      Developer.new('Ivan2','Kovac2',['rails','php']),
      Developer.new('Ivan3','Kovac3',['ruby','php'])
    ]
#premapira jedan niz na drugi
    #@devs=developers.map do |dev|
      #id dev.first_name=='Ivan'
      #return dev
      #dev if dev.has_skill?(params[:filter])
      @devs=developers.select do |dev|
        dev if dev.has_skill?(params[:filter])
      end

    end


  def help
    puts params.inspect
    @page=params[:action].capitalize
    @filter=params[:filter]
    @sort=params[:sort]
  end

end
class Developer
  attr_accessor :first_name, :last_name, :skills
  def initialize(first_name, last_name,skills=[])
    @first_name, @last_name, @skills= first_name, last_name, skills
  end
  def  has_skill?(skill)
    skills.include?(skill)
  end
  def to_s
  "#{first_name}, #{last_name}"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>About page</h1>

<h2>Developers</h2>
<ul>
  <% @devs.each do |dev|%>
  <li><%= dev %></li>
  <% end %>
</ul>

app/views/home/help.html.erb
<h1><%= @page %> page</h1>
<h2><%= @filter %></h2>
<h3><%= @sort %></h3>

app/views/home/index.html.erb
<h1>Welcome to Home page</h1>
<h2>Developers</h2>
<ul>
  <% @devs.each do |dev|%>
  <li><%= dev %></li>
  <% end %>
</ul>

app/views/home/login.html.erb
<h1>Login page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
  <div id="menu">
    <ul>
      <li><a href="<%=root_url%>">Home</a></li>
      <li><a href="<%=about_url%>">About</a></li>
      <li><a href="<%=help_url%>">Help</a></li>
    </ul>
    <br>
    <ul>
      <li><%= link_to('Home', root_path) %></li>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to 'Help', help_path %></li>

    </ul>
  </div>

<div id="content">

<%= yield %>
</div>
</div>
</body>
</html>